home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),

]

product/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment')
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),

]

project2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('',include('home.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),


    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('error/', views.error, name='error'),

    path('category/<int:id>/<slug:slug>/',views.category_products,name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('content/<int:id>/<slug:slug>/', views.contentdetail, name='contentdetail'),
    path('menu/<int:id>/',views.menu,name='menu'),

    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.product_search_auto,name='product_search_auto'),
    path('logout/', views.logout_view,name='logout_view'),
    path('login/', views.login_view,name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=225)
    keywords = models.CharField(max_length=225)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=100)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True,max_length=20)
    smtpemail = models.CharField(blank=True,max_length=20)
    smtppassword = models.CharField(blank=True,max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='image/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    aboutus =RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=150)
    email = models.CharField(blank=True, max_length=150)
    subject = models.CharField(blank=True, max_length=150)
    message = models.CharField(blank=True, max_length=150)
    status = models.CharField(max_length=150,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=150)
    note = models.CharField(blank=True, max_length=150)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name




class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name'     : TextInput(attrs={'class': 'input', 'placeholder': 'Name & Surname'}),
            'subject'  : TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email'    : TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
            'message'  : TextInput(attrs={'class': 'input', 'placeholder': 'Your Message', 'rows': '5'}),
        }


class UserProfile(models.Model):
    user= models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=150)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=150)
    country = models.CharField(blank=True, max_length=15)
    image = models.ImageField(blank=True, upload_to='image/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' ' +self.user.last_name + '[' +self.user.username + '] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

class UserProfileForm(ModelForm):
        class Meta:
            model = UserProfile
            fields = ['phone', 'address', 'city', 'country','image']

product/models.py
from ckeditor.widgets import CKEditorWidget
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Select, FileInput
from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

from home.models import UserProfile


class Category(MPTTModel):
    STATUS =(
        ('True','Evet'),
        ('False','Hayır'),
    )
    title = models.CharField(max_length=100)
    description = models.CharField(blank=True, max_length=225)
    keywords = models.CharField(blank=True, max_length=225)
    image=models.ImageField(blank=True,upload_to='image/')
    status=models.CharField(max_length=10, choices=STATUS)
    slug=models.SlugField(null=False,unique=True)
    parent= TreeForeignKey('self',blank=True,null=True, related_name='children', on_delete=models.CASCADE)
    create_at= models.DateTimeField(auto_now_add=True)
    update_at= models.DateTimeField(auto_now=True)

    class MPTTMeta:

        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k=self.parent
        while k is not None:
            full_path.append(k.title)
            k=k.parent
        return ' / '.join(full_path[::-1])


    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug':self.slug})

class Product(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )


    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category= models.ForeignKey(Category,on_delete=models.CASCADE)
    title = models.CharField(blank=True, max_length=150)
    isim = models.CharField(blank=True, max_length=150)
    email = models.CharField(blank=True, max_length=150)
    telefon = models.CharField(blank=True, max_length=150)
    description = models.CharField(blank=True, max_length=225)
    keywords = models.CharField(blank=True, max_length=225)
    image = models.ImageField(blank=True, upload_to='image/')
    price=models.FloatField()
    marka = models.CharField(blank=True, max_length=150)
    model = models.CharField(blank=True, max_length=225)
    modelyili = models.IntegerField()
    km = models.IntegerField()
    amount = models.IntegerField()
    yakit = models.CharField(blank=True, max_length=225)
    vites = models.CharField(blank=True, max_length=225)
    govde = models.CharField(blank=True, max_length=150)
    disrenk = models.CharField(blank=True, max_length=225)
    icrenk = models.CharField(blank=True, max_length=225)
    doseme = models.CharField(blank=True, max_length=225)
    kaplama = models.CharField(blank=True, max_length=225)
    motorhacmi = models.IntegerField()
    motorgucu = models.IntegerField()
    detail=RichTextUploadingField()
    slug = models.SlugField(null=False,unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title


    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

    def catimg_tag(self):
        return mark_safe((Category.status))

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})



class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['category' ,'title', 'slug', 'keywords', 'description', 'image', 'detail','price','marka','disrenk','model','modelyili','km','amount','yakit','vites','govde',
                  'icrenk','doseme','kaplama','motorhacmi','motorgucu', 'isim','email','telefon']
        widgets = {
            'title'     : TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'slug'  : TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'keywords'    : TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'description'  : TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'category': Select(attrs={'class': 'input', 'placeholder': ''},choices=Category.objects.all()),
            'image': FileInput(attrs={'class': 'input', 'placeholder': ''}),
            'detail': CKEditorWidget(),
            'price':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'marka':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'model':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'modelyili':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'km':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'amount':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'yakit':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'vites':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'govde':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'icrenk':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'disrenk':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'doseme':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'kaplama':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'motorhacmi':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'motorgucu':TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'isim' : TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'email' : TextInput(attrs={'class': 'input', 'placeholder': ''}),
            'telefon' :TextInput(attrs={'class': 'input', 'placeholder': ''}),
        }


class Images(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    title = models.CharField(max_length=50,blank=True)
    image = models.ImageField(blank=True, upload_to='image/')
    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

class ImagesForm(ModelForm):
    class Meta:
        model = Images
        fields = ['title', 'image']

class Comment(models.Model):
    STATUS = (
        ('New','Yeni'),
        ('True','Evet'),
        ('False','Hayır'),
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.TextField(max_length=200)
    status = models.CharField(max_length=10,choices=STATUS, default='New')
    ip= models.CharField(max_length=50, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment']

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)
    catid = forms.IntegerField()


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30,label='Kullanıcı Adı:')
    email = forms.EmailField(max_length=30,label='Email:')
    first_name=forms.CharField(max_length=30,label='Ad:')
    last_name=forms.CharField(max_length=30,label='Soyad:')

    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password1','password2')

product/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from product.models import CommentForm, Comment


def index(request):
    return HttpResponse("Product Page")

@login_required(login_url='/login')
def addcomment(request,id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            current_user = request.user

            data=Comment()
            data.user_id = current_user.id
            data.product_id=id
            data.subject = form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.ip =request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request,"Yorumunuz başarı ile gönderilmiştir.")

            return HttpResponseRedirect(url)

    messages.warning(request, "Kaydedilme işlemi gerçekleşmedi")
    return HttpResponseRedirect(url)

home/templates/content_detail.html
{% extends "homebase.html" %}
{% load static %}
{% block title %}{{  setting.company }}{% endblock %}
{% block keywords %}{{  setting.keywords }}{% endblock %}
{% block description %}{{  setting.description }}{% endblock %}

{% block head %}
    <link rel="icon" sizes="32x32"   type="image/png" href='{{ setting.icon.url }}' />

{% endblock %}


{% block content %}
  <div class="page-title" style="background-image: url({% static 'images/background01.jpg' %});">
			<div class="inner">
				<div class="container">
					<div class="title">MENU</div> <!-- end .title -->
				</div> <!-- end .container -->
			</div> <!-- end .inner -->
		</div> <!-- end .page-title -->

<div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">ANASAYFA</a></li>
                <li class="active">MENU</li>
            </ul>

         </div>
    </div>

        <div class="inner">
            <div class="container">
                <div>
                 <h4>  <b> {{ content.title }}</b></h4><p></p>

                </div>
                <div class="">
                    <img src="{{ content.image.url }}" height="300"  ><p></p>
                </div>
                <div class="">

                    {{ content.detail|safe }}<p></p><p></p>


                </div>


                </div> <!-- end .container -->
            </div> <!-- end .inner -->


{% endblock %}

home/templates/error_page.html
{% extends "homebase.html" %}
{% load static %}
{% block title %}{{  setting.company }}{% endblock %}
{% block keywords %}{{  setting.keywords }}{% endblock %}
{% block description %}{{  setting.description }}{% endblock %}

{% block head %}
    <link rel="icon" sizes="32x32"   type="image/png" href='{{ setting.icon.url }}' />

{% endblock %}


{% block content %}
  <div class="page-title" style="background-image: url({% static 'images/background01.jpg' %});">
			<div class="inner">
				<div class="container">
					<div class="title">HATA</div> <!-- end .title -->
				</div> <!-- end .container -->
			</div> <!-- end .inner -->
		</div> <!-- end .page-title -->

<div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">ANASAYFA</a></li>
                <li class="active">HATA</li>
            </ul>

         </div>
    </div>
		<section class="section white">
			<div class="inner">
				<div class="container">
                    <h1>ARADIĞINIZ İÇERİK BULUNAMADI</h1>

                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{message.tags}}" role="alert">
                                {{ message }}
                            </div>
                        {%endfor%}
                    {% endif %}

				</div> <!-- end .container -->
			</div> <!-- end .inner -->
		</section> <!-- end .section -->

{% endblock %}

home/templates/product_detail.html
{% extends "homebase.html" %}
{% load mptt_tags %}
{% load static %}
{% block title %}{{  product.title }}{% endblock %}
{% block keywords %}{{  product.keywords }}{% endblock %}
{% block description %}{{  product.description }}{% endblock %}

{% block head %}
    <link rel="icon" sizes="32x32"   type="image/png" href='{{ setting.icon.url }}' />

{% endblock %}


{% block content %}
    <div class="page-title" style="background-image: url({% static 'images/background01.jpg' %});">
        <div class="inner">
            <div class="container">
                <div class="title">{{  product.description }}</div> <!-- end .title -->
            </div> <!-- end .container -->
        </div> <!-- end .inner -->
    </div> <!-- end .page-title -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">ANASAYFA</a></li>
                <li><a href="/category/{{ product.category_id }}/{{ product.category.slug }}">{{ product.category }}</a></li>
                <li class="active">{{ product.description }}</li>
            </ul>

        </div>
    </div>

    <section class="section white">
        <div class="inner">
            <div class="container">
                <div class="car-details">
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="clearfix">
                                <div class="title">{{ product.description }}<span></span></div>
                            </div>

                            <div id="car-details-slider" class="image">
                                <div class="item"><img src=" {{ product.image.url }}"  alt="alt" style="height: 500px" class="img-responsive"></div>
                                {% for rs in images %}
                                    <div class="item"><img src="{{ rs.image.url }}" alt="alt" style="height: 500px" class="img-responsive"></div>
                                {% endfor %}
                            </div>


                            <div class="tabpanel border" role="tabpanel">
                                <ul class="nav nav-tabs" role="tablist">
                                    <li role="presentation" class="active"><a href="#heading-tab4" aria-controls="heading-tab4" role="tab" data-toggle="tab">DETAY</a></li>
                                    <li role="presentation"><a href="#heading-tab5" aria-controls="heading-tab5" role="tab" data-toggle="tab">YORUMLAR</a></li>
                                    <li role="presentation"><a href="#heading-tab6" aria-controls="heading-tab6" role="tab" data-toggle="tab">İLETİŞİM</a></li>
                                </ul> <!-- end .nav-tabs -->
                                <div class="tab-content">
                                    <div role="tabpanel" class="tab-pane fade in active" id="heading-tab4">
                                        {{ product.detail | safe }}
                                    </div> <!-- end .tab-panel -->
                                    <div role="tabpanel" class="tab-pane fade" id="heading-tab5">
                                        <div class="comments">

                                            <div class="comment clearfix">
                                                {% for rs in comments %}

                                                    <div class="content">
                                                        <p><a>{{ rs.user.first_name }} {{ rs.user.last_name }}, </a></p>
                                                        <p><b>{{ rs.subject }}</b></p>
                                                        <p>{{ rs.comment }}</p>
                                                        <a class="reply">{{ rs.create_at }}</a>
                                                    </div> <!-- end .content -->
                                                {% endfor %}
                                            </div> <!-- end .comment -->

                                        </div> <!-- end .comments -->

                                        <div class="leave-reply">
                                            <h4>Yorum Ekle</h4>
                                            <form action="/product/addcomment/{{ product.id }}" method="post">
                                                {% csrf_token %}
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                        <div class="form-group">
                                                            <input class="input"  type="text" name="subject" id="id_subject" placeholder="Konu" />
                                                        </div> <!-- end .form-group -->
                                                    </div> <!-- end .col-sm-6 -->
                                                    <div class="col-sm-6">
                                                        <div class="form-group">

                                                        </div> <!-- end .form-group -->
                                                    </div> <!-- end .col-sm-6 -->
                                                </div> <!-- end .row -->
                                                <div class="form-group">
                                                    <textarea class="input" name="comment" id="id_comment" required placeholder="Mesajınız" ></textarea>
                                                </div> <!-- end .form-group -->
                                                {% if messages %}
                                                    {% for message in messages %}
                                                        <div class="alert alert-{{message.tags}}" role="alert">
                                                            {{ message }}
                                                        </div>
                                                    {%endfor%}
                                                {% endif %}
                                                {% if user.id is not None %}
                                                    <input type="submit" value="Gönder" class="button solid light-blue" />
                                                {% else %}
                                                    Yorum eklemek için <a href="/login"> Üye Olunuz!</a>
                                                {% endif %}
                                            </form>
                                        </div> <!-- end .leave-reply -->


                                    </div> <!-- end .tab-panel -->
                                    <div role="tabpanel" class="tab-pane fade" id="heading-tab6">

                                        <p><h5><b>Satıcı Bilgileri</b></h5></p>
                                        <div class="content">
                                            <div class="item clearfix">
                                                <div class="option"><b>AD SOYAD: </b>{{ product.isim }}</div>
                                            </div> <!-- end .item -->
                                            <div class="item clearfix">
                                                <div class="option"><b>TELEFON: </b>{{ product.telefon }}</div>
                                            </div> <!-- end .item -->
                                            <div class="item clearfix">
                                                <div class="option"><b>EMAİL: </b>{{ product.email }}</div>
                                            </div> <!-- end .item -->

                                        </div>

                                    </div> <!-- end .tab-panel -->
                                </div> <!-- end .tab-content -->
                            </div> <!-- end .tabpanel -->





                        </div> <!-- end .col-sm-8 -->
                        <div class="col-sm-4">
                            <div class="price">${{ product.price }} <span>/ Satılık</span></div>
                            <div class="main-car-details">
                                <div class="item clearfix">
                                    <div class="option">Marka</div>
                                    <div class="option-content">{{ product.marka }}</div>
                                </div> <!-- end .item -->
                                <div class="item clearfix">
                                    <div class="option">Model</div>
                                    <div class="option-content">{{ product.model }}</div>
                                </div> <!-- end .item -->
                                <div class="item clearfix">
                                    <div class="option">Model Yılı</div>
                                    <div class="option-content">{{ product.modelyili }}</div>
                                </div> <!-- end .item -->
                                <div class="item clearfix">
                                    <div class="option">Kilometre</div>
                                    <div class="option-content">{{ product.km }}</div>
                                </div> <!-- end .item -->
                                <div class="item clearfix">
                                    <div class="option">Yakıt</div>
                                    <div class="option-content">{{ product.yakit }}</div>
                                </div> <!-- end .item -->
                                <div class="item clearfix">
                                    <div class="option">Vites</div>
                                    <div class="option-content">{{ product.vites }}</div>
                                </div> <!-- end .item -->
                                <div class="item clearfix">
                                    <div class="option">Gövde Tipi</div>
                                    <div class="option-content">{{ product.govde }}</div>
                                </div> <!-- end .item -->
                                <div class="item clearfix">
                                    <div class="option">Dış Renk</div>
                                    <div class="option-content">{{ product.disrenk }}</div>
                                </div> <!-- end .item -->
                                <div class="item clearfix">
                                    <div class="option">İç Renk</div>
                                    <div class="option-content">{{ product.icrenk }}</div>
                                </div> <!-- end .item -->
                                <div class="item clearfix">
                                    <div class="option">Döşeme</div>
                                    <div class="option-content">{{ product.doseme }}</div>
                                </div> <!-- end .item -->
                                <div class="item clearfix">
                                    <div class="option">Kaplama</div>
                                    <div class="option-content">{{ product.kaplama }}</div>
                                </div> <!-- end .item -->
                                <div class="item clearfix">
                                    <div class="option">Motor Hacmi</div>
                                    <div class="option-content">{{ product.motorhacmi }}</div>
                                </div> <!-- end .item -->
                                <div class="item clearfix">
                                    <div class="option">Motor Gücü</div>
                                    <div class="option-content">{{ product.motorgucu }}</div>
                                </div> <!-- end .item -->
                            </div> <!-- end .main-car-details -->
                        </div> <!-- end .col-sm-4 -->
                    </div> <!-- end .row -->
                </div> <!-- end .car-details -->
            </div> <!-- end .container -->
        </div> <!-- end .inner -->
    </section> <!-- end .section -->



{% endblock %}

home/templates/referanslar.html
{% extends "homebase.html" %}
{% load static %}
{% block title %}{{  setting.company }}{% endblock %}
{% block keywords %}{{  setting.keywords }}{% endblock %}
{% block description %}{{  setting.description }}{% endblock %}

{% block head %}
    <link rel="icon" sizes="32x32"   type="image/png" href='{{ setting.icon.url }}' />

{% endblock %}


{% block content %}
  <div class="page-title" style="background-image: url({% static 'images/background01.jpg' %});">
			<div class="inner">
				<div class="container">
					<div class="title">REFERANSLAR</div> <!-- end .title -->
				</div> <!-- end .container -->
			</div> <!-- end .inner -->
		</div> <!-- end .page-title -->

<div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">ANASAYFA</a></li>
                <li class="active">REFERANSLAR</li>
            </ul>

         </div>
    </div>
		<section class="section white">
			<div class="inner">
				<div class="container">
					 {{ setting.references | safe }}


				</div> <!-- end .container -->
			</div> <!-- end .inner -->
		</section> <!-- end .section -->

{% endblock %}

home/templates/sidebar.html
{% load mptt_tags %}

<li>
    <a href="/">ARABALAR</a>
    <ul>
        {% recursetree category %}
            {% if  node.is_leaf_node %}
                <li><a href="/category/{{ node.id }}/{{ node.slug }}">{{ node.title }}</a></li>
            {% endif %}
            {% if not node.is_leaf_node %}
                <li><a href="/category/{{ node.id }}/{{ node.slug }}">{{ node.title }}</a>
                    <ul>{{ children }} </ul></li>
            {% endif %}
        {% endrecursetree %}
    </ul>
</li>