home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),

]

project2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('',include('home.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),


    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('error/', views.error, name='error'),

    path('category/<int:id>/<slug:slug>/',views.category_products,name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('content/<int:id>/<slug:slug>/', views.contentdetail, name='contentdetail'),
    path('menu/<int:id>/',views.menu,name='menu'),

    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.product_search_auto,name='product_search_auto'),
    path('logout/', views.logout_view,name='logout_view'),
    path('login/', views.login_view,name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('update/',views.user_update,name='user_update'),
    path('password/',views.change_password,name='change_password'),
    path('comments/',views.comments,name='comments'),
    path('deletecomment/<int:id>',views.deletecomment,name='deletecomment'),

    path('addcontent/',views.addcontent,name='addcontent'),
    path('content/',views.contents,name='content'),
    path('contentedit/<int:id>',views.contentedit,name='contentedit'),
    path('contentdelete/<int:id>',views.contentdelete,name='deletecomment'),
    path('contentaddimage/<int:id>', views.contentaddimage, name='contentaddimage'),

    #path('addcomment/<int:id>', views.addcomment, name='addcomment')
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),

]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=225)
    keywords = models.CharField(max_length=225)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=100)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True,max_length=20)
    smtpemail = models.CharField(blank=True,max_length=20)
    smtppassword = models.CharField(blank=True,max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='image/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    aboutus =RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=150)
    email = models.CharField(blank=True, max_length=150)
    subject = models.CharField(blank=True, max_length=150)
    message = models.CharField(blank=True, max_length=150)
    status = models.CharField(max_length=150,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=150)
    note = models.CharField(blank=True, max_length=150)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name




class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name'     : TextInput(attrs={'class': 'input', 'placeholder': 'Name & Surname'}),
            'subject'  : TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email'    : TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
            'message'  : TextInput(attrs={'class': 'input', 'placeholder': 'Your Message', 'rows': '5'}),
        }


class UserProfile(models.Model):
    user= models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=150)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=150)
    country = models.CharField(blank=True, max_length=15)
    image = models.ImageField(blank=True, upload_to='image/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' ' +self.user.last_name + '[' +self.user.username + '] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

class UserProfileForm(ModelForm):
        class Meta:
            model = UserProfile
            fields = ['phone', 'address', 'city', 'country','image']

user/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput, FileInput, Select, EmailInput

from home.models import UserProfile




class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name')
        widgets ={
            'username' :TextInput(attrs={'class':'input','placeholder':'username'}),
            'email': EmailInput(attrs={'class': 'input', 'placeholder': 'email'}),
            'first_name': TextInput(attrs={'class': 'input', 'placeholder': 'firt_name'}),
            'last_name': TextInput(attrs={'class': 'input', 'placeholder': 'last_name'}),
        }

CITY = [
    ('Istanbul','Istanbul'),
    ('Ankara','Ankara'),
    ('Izmir','Izmir'),
]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields=('phone','address','city','country','image')
        widgets = {
            'phone': TextInput(attrs={'class': 'input', 'placeholder': 'phone'}),
            'address': TextInput(attrs={'class': 'input', 'placeholder': 'address'}),
            'city': Select(attrs={'class': 'input', 'placeholder': 'city'},choices=CITY),
            'country': TextInput(attrs={'class': 'input', 'placeholder': 'country'}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
        }

user/templates/change_password.html
{% extends "homebase.html" %}
{% load static %}
{% block title %}{{  setting.company }}{% endblock %}
{% block keywords %}{{  setting.keywords }}{% endblock %}
{% block description %}{{  setting.description }}{% endblock %}

{% block head %}
    <link rel="icon" sizes="32x32"   type="image/png" href='{{ setting.icon.url }}' />

{% endblock %}


{% block content %}
  <div class="page-title" style="background-image: url({% static 'images/background01.jpg' %});">
			<div class="inner">
				<div class="container">
					<div class="title">ŞİFRE GÜNCELLEME</div> <!-- end .title -->
				</div> <!-- end .container -->
			</div> <!-- end .inner -->
		</div> <!-- end .page-title -->

<div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">ANASAYFA</a></li>
                <li class="active">PROFİL</li>
            </ul>

         </div>
    </div>
		<section class="section white">
			<div class="inner">
				<div class="container">
					<div class="row">

                        <div class="col-md-2">


                                {% include "user_panel.html" %}


						</div> <!-- end .col-sm-7 -->

						<div class="column-spacer"></div>

                        <div class="col-md-10">
                            <div class="billing-details">

                                <div class="car-details alt">

                                <div class="specifications clearfix">


                                    {% if messages %}
                                       {% for message in messages %}
                                          <div style="color: #d43f3a; font-size: medium" >
                                            {{ message |safe }}
                                          </div>
                                       {% endfor %}
                                    {% endif %}

                                    <form method="post">
                                        {% csrf_token %}
                                        {% for field in form %}
                                        <p>
                                            {{ field.label_tag }}<br>
                                            {{ field }}
                                            {% if field.help_text %}
                                               <small style="color: black">{{ field.help_text }}</small>
                                            {% endif %}
                                            {% for error in field.errors %}
                                                  <p>{{ error }}</p>
                                            {% endfor %}
                                        </p>
                                        {% endfor %}

                                         <button class="button solid yellow size1" type="submit">Değişikliği Kaydet</button>
                                    </form>

                                </div> <!-- end .specifications -->
                                </div>







                            </div> <!-- end .col-sm-5 -->

					</div>
				</div> <!-- end .container -->
			</div> <!-- end .inner -->
		</section> <!-- end .section -->
{% endblock %}

user/templates/content_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GALERİ</title>
</head>
<body>
<h2>{{ content.title }}</h2>
<hr>
{% if messages %}
    {% for message in messages %}
       <div class="alert alert--{{ message.tags }}" role="alert">
           {{ message|safe }}
       </div>
    {% endfor %}
{% endif %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="content_id" id="id_content_id" value="{{ product.id }}">
    <label for="id_title">Başlık:</label>
    <input type="text" name="title" class="input" placeholder="Başlık" maxlength="50" id="id_title"></p>

    <label for="id_image">Resim:</label>
    <input type="file" name="image" class="input" placeholder="Resim" accept="image/*" id="id_image"></p>
    <button class="primary-btn" type="submit">Resim Yükle</button>
</form>


<hr>
<h4>Yüklenen Resimler</h4>
{% for rs in images %}
   <img src="{{ rs.image.url }}" height="200">
{% endfor %}
</body>
</html>

user/templates/user_addcontent.html
{% extends "homebase.html" %}
{% load static %}
{% block title %}{{  setting.company }}{% endblock %}
{% block keywords %}{{  setting.keywords }}{% endblock %}
{% block description %}{{  setting.description }}{% endblock %}

{% block head %}
    <link rel="icon" sizes="32x32"   type="image/png" href='{{ setting.icon.url }}' />
    {% load static %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}


{% block content %}
  <div class="page-title" style="background-image: url({% static 'images/background01.jpg' %});">
			<div class="inner">
				<div class="container">
					<div class="title">İLAN EKLE</div> <!-- end .title -->
				</div> <!-- end .container -->
			</div> <!-- end .inner -->
		</div> <!-- end .page-title -->

<div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">ANASAYFA</a></li>
                <li class="active">İLAN EKLE</li>
            </ul>

         </div>
</div>
    <section class="section white">
        <div class="inner">
            <div class="container">
                <div class="row">

                    <div class="col-md-2">


                        {% include "user_panel.html" %}


                    </div> <!-- end .col-sm-7 -->

                    <div class="column-spacer"></div>

                    <div class="col-md-10">
                        <div class="billing-details">

                            <div class="car-details alt">

                                <div class="specifications clearfix">


                                    <div class="content-section">
                                        {% load static %}
                                        <form method="POST" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <fieldset class="form-group">
                                                {{ form.media }}
                                                {{ form.as_p }}
                                            </fieldset>
                                            <div class="form-group">
                                                <input type="submit" class="button solid yellow size1"></input>
                                            </div>
                                        </form>
                                    </div>




                                </div> <!-- end .specifications -->
                            </div>







                        </div> <!-- end .col-sm-5 -->

                    </div>
                </div> <!-- end .container -->
            </div> <!-- end .inner -->
        </div>
    </section> <!-- end .section -->
{% endblock %}

user/templates/user_comments.html
{% extends "homebase.html" %}
{% load static %}
{% block title %}{{  setting.company }}{% endblock %}
{% block keywords %}{{  setting.keywords }}{% endblock %}
{% block description %}{{  setting.description }}{% endblock %}

{% block head %}
    <link rel="icon" sizes="32x32"   type="image/png" href='{{ setting.icon.url }}' />

{% endblock %}


{% block content %}
  <div class="page-title" style="background-image: url({% static 'images/background01.jpg' %});">
			<div class="inner">
				<div class="container">
					<div class="title">KULLANICI PROFİLİ</div> <!-- end .title -->
				</div> <!-- end .container -->
			</div> <!-- end .inner -->
		</div> <!-- end .page-title -->

<div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">ANASAYFA</a></li>
                <li class="active">YORUMLAR</li>
            </ul>

         </div>
    </div>
		<section class="section white">
			<div class="inner">
                <div class="container">
                    <div class="row">

                        <div class="col-md-2">


                            {% include "user_panel.html" %}


                        </div> <!-- end .col-sm-7 -->

                        <div class="column-spacer"></div>

                        <div class="col-md-10">
                            <div class="billing-details">

                                <div class="car-details alt">

                                    <div class="specifications clearfix">

                                        <h2>Yorumlar</h2>


                                        <img src="{% static 'images/details.png'%}" alt="background" class="bg">
                                        <div class="content">
                                            <div class="">
                                                <table class="-shopping-cart-table table">
                                                    <tr>
                                                        <th class="text-left">Araç</th>
                                                        <th class="text-left">Konu</th>
                                                        <th class="text-left">Yorum</th>
                                                        <th class="text-left">Statü</th>
                                                        <th class="text-left">Tarih</th>
                                                        <th class="text-left">Detay</th>
                                                    </tr>
                                                    {% for rs in comments %}
                                                    <tr>
                                                        <th class="text-left">
                                                            <a href="/product/{{ rs.product_id }}/{{ rs.product.slug }}">
                                                            {{ rs.product.title }}
                                                            </a>
                                                        </th>
                                                        <th class="text-left">{{ rs.subject }}</th>
                                                        <th class="text-left">{{rs.comment}}</th>
                                                        <th class="text-left">{{rs.status}}</th>
                                                        <th class="text-left">{{rs.create_at}}</th>
                                                        <th class="text-left"> <a class="button solid yellow size1" href="/user/deletecomment/{{ rs.id }}" onclick="return confirm('Silmek istediğine emin misin ?')" >Sil</a></th>
                                                    </tr>
                                                    {% endfor %}
                                                </table>
                                             {% if messages %}
                                            {% for message in messages %}
                                                <div class="alert alert-{{message.tags}}" role="alert">
                                                    {{ message }}
                                                </div>
                                            {%endfor%}
                                        {% endif %}




                                            </div> <!-- end .row -->
                                        </div> <!-- end .content -->
                                    </div> <!-- end .specifications -->
                                </div>





                            </div>

                        </div> <!-- end .col-sm-5 -->

                    </div>
                </div> <!-- end .container -->
			</div> <!-- end .inner -->
		</section> <!-- end .section -->
{% endblock %}

user/templates/user_contents.html
{% extends "homebase.html" %}
{% load static %}
{% block title %}{{  setting.company }}{% endblock %}
{% block keywords %}{{  setting.keywords }}{% endblock %}
{% block description %}{{  setting.description }}{% endblock %}

{% block head %}
    <link rel="icon" sizes="32x32"   type="image/png" href='{{ setting.icon.url }}' />

{% endblock %}


{% block content %}
  <div class="page-title" style="background-image: url({% static 'images/background01.jpg' %});">
			<div class="inner">
				<div class="container">
					<div class="title">KULLANICI İLANI</div> <!-- end .title -->
				</div> <!-- end .container -->
			</div> <!-- end .inner -->
		</div> <!-- end .page-title -->

<div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">ANASAYFA</a></li>
                <li class="active">İLANLAR</li>
            </ul>

         </div>
    </div>
		<section class="section white">
			<div class="inner">
                <div class="container">
                    <div class="row">

                        <div class="col-md-2">


                            {% include "user_panel.html" %}


                        </div> <!-- end .col-sm-7 -->

                        <div class="column-spacer"></div>


                        <div class="col-md-10">
                            <div class="section-title">
                                <h4 class="title">İlanlarım </h4>
                            </div>

                            <table class="-shopping-cart-table table">
                                <tr>
                                    <th class="text-left">Resim</th>
                                    <th class="text-left">Model</th>
                                    <th class="text-left">Marka</th>
                                    <th class="text-left">Onay</th>
                                    <th class="text-left">Galeri</th>
                                    <th class="text-left">Tarih</th>
                                    <th class="text-left">Detay</th>
                                </tr>
                                {% for rs in product %}
                                <tr>
                                    <th class="text-left">
                                        <a href="/product/{{ rs.id }}/{{ rs.slug }}">
                                        <img src="{{ rs.image.url }}" style="height: 50px; width: 70px;" ></a></th>
                                    <th class="text-left">
                                        <a href="/product/{{ rs.id }}/{{ rs.slug }}">
                                            {{ rs.title }}</a></th>

                                    <th class="text-left">{{rs.category.title}}</th>
                                    <th class="text-left">{{rs.status}}</th>
                                    <th class="text-left">
                                        <a href="javascript:;" onclick="window.open('/user/contentaddimage/{{ rs.id }}','gallery','height=600,width=800,top=50,left=150')">Galeri</a>
                                    </th>
                                    <th class="text-left">{{rs.create_at}}</th>
                                    <th class="text-left"><a class="button solid yellow size1" href="/user/contentedit/{{ rs.id }}">Düzenle</a></th>
                                    <th class="text-left"><a onclick="return confirm('Silmek İstediğinize emin misiniz?')"
                                                             class="button solid yellow size1" href="/user/contentdelete/{{ rs.id }}">Sil</a> </th>
                                </tr>
                                {% endfor %}
                            </table>


                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-{{message.tags}}" role="alert">
                                        {{ message }}
                                    </div>
                                {%endfor%}
                            {% endif %}






                        </div> <!-- end .col-sm-5 -->

                    </div>
                </div> <!-- end .container -->
			</div> <!-- end .inner -->
		</section> <!-- end .section -->
{% endblock %}

user/templates/user_panel.html
<div class="widget">
    <h5 class="title">HESABIM</h5>
    <ul class="fa-ul list-unstyled">
        <li><i class="fa-li fa fa-caret-right"></i><a href="/user">Kullanıcı Profili</a></li>
        <li><i class="fa-li fa fa-caret-right"></i><a href="/user/comments">Yorumlar</a></li>
        <li><i class="fa-li fa fa-caret-right"></i><a href="/user/content">İlanlar</a></li>
        <li><i class="fa-li fa fa-caret-right"></i><a href="/user/addcontent">İlan Ver</a></li>
        <li><i class="fa-li fa fa-caret-right"></i><a href="/logout">Çıkış</a></li>

    </ul>
</div> <!-- end .widget -->

user/templates/user_profile.html
{% extends "homebase.html" %}
{% load static %}
{% block title %}{{  setting.company }}{% endblock %}
{% block keywords %}{{  setting.keywords }}{% endblock %}
{% block description %}{{  setting.description }}{% endblock %}

{% block head %}
    <link rel="icon" sizes="32x32"   type="image/png" href='{{ setting.icon.url }}' />

{% endblock %}


{% block content %}
  <div class="page-title" style="background-image: url({% static 'images/background01.jpg' %});">
			<div class="inner">
				<div class="container">
					<div class="title">KULLANICI PROFİLİ</div> <!-- end .title -->
				</div> <!-- end .container -->
			</div> <!-- end .inner -->
		</div> <!-- end .page-title -->

<div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">ANASAYFA</a></li>
                <li class="active">PROFİL</li>
            </ul>

         </div>
    </div>
		<section class="section white">
			<div class="inner">
				<div class="container">
					<div class="row">

                        <div class="col-md-2">


                                {% include "user_panel.html" %}


						</div> <!-- end .col-sm-7 -->

						<div class="column-spacer"></div>

                        <div class="col-md-10">
                            <div class="billing-details">

                                <div class="car-details alt">

                                <div class="specifications clearfix">
                                    <h2>Kullanıcı Bilgileri</h2>

                                    <img src="{% static 'images/details.png'%}" alt="background" class="bg">
                                    <div class="content">
                                        <div class="">

                                                <div class="item clearfix">
                                                    <div class=""><img src="{{ profile.image.url }}" style="height: 120px; weight:100px "></div>

                                                </div> <!-- end .item -->
                                                <div class="item clearfix">
                                                    <div class="option">Adı</div>
                                                    <div class="option-content">{{ profile.user.first_name }}</div>
                                                </div> <!-- end .item -->
                                                <div class="item clearfix">
                                                    <div class="option">Soyadı</div>
                                                    <div class="option-content">{{ profile.user.last_name }}</div>
                                                </div> <!-- end .item -->

                                                <div class="item clearfix">
                                                    <div class="option">Email</div>
                                                    <div class="option-content">{{ profile.user.email }}</div>
                                                </div> <!-- end .item -->
                                                <div class="item clearfix">
                                                    <div class="option">Telefon</div>
                                                    <div class="option-content">{{ profile.phone }}</div>
                                                </div> <!-- end .item -->
                                                <div class="item clearfix">
                                                    <div class="option">Adres:</div>
                                                    <div class="option-content">{{ profile.address }}</div>
                                                </div> <!-- end .item -->

                                                <div class="item clearfix">
                                                    <div class="option">Şehir</div>
                                                    <div class="option-content">{{ profile.city }}</div>
                                                </div> <!-- end .item -->
                                                <div class="item clearfix">
                                                    <div class="option">Ülke</div>
                                                    <div class="option-content">{{ profile.country }}</div>
                                                </div> <!-- end .item -->
                                                <div class="">

                                                    <a href="/user/update" class="button solid yellow size1">Güncelleme</a>
                                                    <a href="/user/password" class="button solid yellow size1">Şifre Değiştirme</a>
                                                    <p></p>

                                                </div> <!-- end .item -->
                                            {% if messages %}
                                                {% for message in messages %}
                                                    <div class="alert alert-{{message.tags}}" role="alert">
                                                        {{ message }}
                                                    </div>
                                                {%endfor%}
                                            {% endif %}



                                        </div> <!-- end .row -->
                                    </div> <!-- end .content -->
                                </div> <!-- end .specifications -->
                                </div>







                            </div> <!-- end .col-sm-5 -->

					</div>
				</div> <!-- end .container -->
			</div> <!-- end .inner -->
            </div>
		</section> <!-- end .section -->
{% endblock %}